In [1]:
import polars as pl
import pandas as pd
import os 
import numpy as np
os.chdir('..')

In [23]:
def convertions(row):
    if row['unit_1'] == 'kg':
        return row['qty'] * 1
    elif row['unit_1'] == 'l':
        return row['qty'] * 1
    elif row['unit_1'] == 'doz':
        return row['qty'] / 0.756
    elif row['unit_1'] =='m3':
        return row['qty'] * 1560
    elif row['unit_1'] == 't':
        return row['qty'] * 907.185
    elif row['unit_1'] == 'kts':
        return row['qty'] * 1
    elif row['unit_1'] == 'pfl':
        return row['qty'] * 0.789
    elif row['unit_1'] == 'gm':
        return row['qty'] * 1000
    else:
        return np.nan

In [12]:
pl.read_csv('data/raw/data.csv', ignore_errors=True)

shape: (2_653_965, 42)
┌───────┬──────┬───────┬────────────────┬───┬────────────┬────────────┬────────────┬──────────┐
│ Trade ┆ Year ┆ Month ┆ Commodity_Code ┆ … ┆ air_cha_mo ┆ ves_cha_mo ┆ cnt_cha_mo ┆ rev_data │
│ ---   ┆ ---  ┆ ---   ┆ ---            ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ str   ┆ i64  ┆ i64   ┆ i64            ┆   ┆ i64        ┆ i64        ┆ i64        ┆ str      │
╞═══════╪══════╪═══════╪════════════════╪═══╪════════════╪════════════╪════════════╪══════════╡
│ i     ┆ 2009 ┆ 7     ┆ 101100000      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ Y        │
│ e     ┆ 2009 ┆ 7     ┆ 101100000      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ Y        │
│ i     ┆ 2009 ┆ 7     ┆ 105110020      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ Y        │
│ i     ┆ 2009 ┆ 7     ┆ 105940000      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ Y        │
│ i     ┆ 2009 ┆ 7     ┆ 105990000      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ Y        │
│ …     ┆ …    ┆ …     ┆ …              ┆ … ┆ …          ┆ …          ┆ …          ┆ …        │
│ i     ┆ 2024 ┆ 2     ┆ 9810001500     ┆ … ┆ 500        ┆ 0          ┆ 0          ┆ N        │
│ i     ┆ 2024 ┆ 2     ┆ 9817005000     ┆ … ┆ 0          ┆ 2500       ┆ 2500       ┆ N        │
│ i     ┆ 2024 ┆ 2     ┆ 9817005000     ┆ … ┆ 0          ┆ 3501       ┆ 3501       ┆ N        │
│ e     ┆ 2024 ┆ 2     ┆ 9880004000     ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ N        │
│ i     ┆ 2024 ┆ 2     ┆ 9880004000     ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ N        │
└───────┴──────┴───────┴────────────────┴───┴────────────┴────────────┴────────────┴──────────┘

In [ ]:
df = pd.read_csv("data/processed/hts_data.csv")
df

In [3]:
df2 = pd.read_csv('data/raw/data.csv', low_memory=False)

In [33]:
df = df2.copy()
df["date"] = pd.to_datetime(df["Year"].astype(str) + "-" + df["Month"].astype(str))
df["date"] = pd.to_datetime(df["date"])

df_imports = df[df["Trade"] == "i"].copy().reset_index(drop=True)
df_imports = df_imports[["Country", "date", "data", 'qty_1', 'qty_2', "unit_1"]]
df_imports["unit_1"] = df_imports["unit_1"].str.lower() 
# standerize all values to kg 
df_imports['qty'] = df_imports['qty_1'] + df_imports['qty_2']
df_imports.drop(['qty_1', 'qty_2'], axis=1, inplace=True)
df_imports['qty2'] = df_imports.apply(convertions, axis=1)
df_imports = df_imports[df_imports['qty'] > 0].copy()
df_imports = df_imports.groupby(['Country', 'date']).sum().reset_index()
df_imports.rename(columns={"data": "imports"}, inplace=True)
df_imports

,Country,date,imports,unit_1,qty
0,Albania,2009-07-01,1174,dozdoz,52.910053
1,Albania,2009-12-01,366,doz,15.873016
2,Albania,2010-07-01,338,doz,15.873016
3,Albania,2010-08-01,547,doz,27.777778
4,Albania,2010-09-01,570,doz,30.423280
...,...,...,...,...,...
14432,Virgin Islands of the United States,2023-10-01,27729,kgkg,23596.000000
14433,Virgin Islands of the United States,2023-11-01,2700,kg,17259.000000
14434,Virgin Islands of the United States,2023-12-01,2700,kg,26846.000000
14435,Virgin Islands of the United States,2024-01-01,16650,pflkg,58264.200000
14436,Virgin Islands of the United States,2024-02-01,2700,kg,16771.000000

In [30]:
df_imports['test'] = df_imports.apply(convertions, axis=1)
df_imports

               Country       date       data  qty_1  qty_2 unit_1    qty  test
0        United States 2009-07-01    3650000     15      0     no     15   NaN
1        United States 2009-07-01      42720  64000      0     no  64000   NaN
2        United States 2009-07-01       6542   2911      0     no   2911   NaN
3        United States 2009-07-01     220000  91164      0     no  91164   NaN
4        United States 2009-07-01      65000  22029      0     no  22029   NaN
...                ...        ...        ...    ...    ...    ...    ...   ...
2102023  United States 2024-02-01      54582      0      0      x      0   NaN
2102024          Italy 2024-02-01       3138    121      0     no    121   NaN
2102025        Vietnam 2024-02-01      28750      0      0      x      0   NaN
2102026          China 2024-02-01       9642      0      0      x      0   NaN
2102027  United States 2024-02-01  176375935      0      0      x      0   NaN

[2102028 rows x 8 columns]

In [ ]:
df_imports['qty']

In [4]:
df = df2.copy()
df["date"] = pd.to_datetime(df["Year"].astype(str) + "-" + df["Month"].astype(str))
df["date"] = pd.to_datetime(df["date"])

df_imports = df[df["Trade"] == "i"].copy().reset_index(drop=True)
df_imports = df_imports[["Country", "date", "data", 'qty_1', 'qty_2', "unit_1"]]

# standerize all values to kg 
df_imports['qty'] = df_imports['qty_1'] + df_imports['qty_2']
df_imports.drop(['qty_1', 'qty_2'], axis=1, inplace=True)
df_imports['qty'] = df_imports.apply(convertions, axis=1)
df_imports = df_imports[df_imports['qty'] > 0].copy()
df_imports = df_imports.groupby(['Country', 'date']).sum().reset_index()
df_imports.rename(columns={"data": "imports"}, inplace=True)

df_exports = df[df["Trade"] == "e"].copy().reset_index(drop=True)
df_exports = df_exports[["Country", "date", "data", "qty_1", "qty_2", "unit_1"]]

# standerize all values to kg 
df_exports['qty'] = df_exports['qty_1'] + df_exports['qty_2']
df_exports.drop(['qty_1', 'qty_2'], axis=1, inplace=True)
df_exports['qty'] = df_exports.apply(convertions, axis=1)
df_exports = df_exports[df_exports['qty'] > 0].copy()
df_exports = df_exports.groupby(['Country', 'date']).sum().reset_index()
df_exports.rename(columns={"data": "exports"}, inplace=True)

# merge dataframes
country_trade = pd.merge(df_exports, df_imports, on=["date", "Country"], how="outer")

# make mising to 0 & make net exports
country_trade["imports"] = country_trade["imports"].fillna(0)
country_trade["exports"] = country_trade["exports"].fillna(0)
country_trade["net_value"] = country_trade["exports"] - country_trade["imports"]

country_trade = country_trade.sort_values(by=["Country", "date"], ascending=True).reset_index(drop=True)

In [6]:
unique_countries = country_trade['Country'].unique()

In [10]:
country_trade

Empty DataFrame
Columns: [exports, unit_1_x, qty_x, Country, date, imports, unit_1_y, qty_y, net_value]
Index: []

In [7]:
all_dates = pd.date_range(start=country_trade['date'].min(), end=country_trade['date'].max(), freq='MS')

ValueError: Neither `start` nor `end` can be NaT

In [ ]:
# Balance the data
unique_countries = country_trade['Country'].unique()
all_dates = pd.date_range(start=country_trade['date'].min(), end=country_trade['date'].max(), freq='MS')
idx = pd.MultiIndex.from_product([unique_countries, all_dates], names=['Country', 'date'])
country_trade = country_trade.set_index(['Country', 'date']).reindex(idx, fill_value=0).reset_index()

In [ ]:
df.to_pickle(os.getcwd() + "/data/raw" + "/data.pkl", ignore_errors=True)